version: '3.9'

services:
  bcv_bot:
    build: .
    container_name: bcv_bot
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
      - ./firebase_key.json:/app/firebase_key.json:ro
    ports:
      - "8080:80"
    restart: always
    healthcheck:
      test: ["CMD", "python", "-c", "print('OK')"]
      interval: 30s
      timeout: 10s
      retries: 3
