version: '3.9'

services:
  bcv-bot:
    build: .
    container_name: bcv_bot
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
      - ./firebase_key.json:/app/firebase_key.json:ro
    restart: always

    healthcheck:
      test: ["CMD", "python", "-c", "print('OK')"]
      interval: 1m
      timeout: 10s
      retries: 3
