version: '3.9'

services:
  bcv_bot:
    build: .
    container_name: bcv_bot
    env_file:
      - .env  # ← usarás el .env de esta rama
    volumes:
      - ./logs:/app/logs
      - ./firebase_key.json:/app/firebase_key.json:ro
    restart: always
    ports:
      - "8080:80"  # ← puerto diferente por si quieres hacer pruebas en paralelo
    healthcheck:
      test: ["CMD", "python", "-c", "print('OK')"]
      interval: 1m
      timeout: 10s
      retries: 3