import { randomBytes, createHash } from 'node:crypto';
import { and, desc, eq, gte, isNull, sql } from 'drizzle-orm';
import type { Database } from '../db/client.js';
import {
  apiKeys,
  apiKeyUsageDaily,
  type ApiKey,
  type ApiKeyUsageDaily,
} from '../db/schema.js';
import { addDays, todayCaracas } from '../lib/dates.js';

/** All issued keys start with this prefix so they're identifiable in logs / leaks. */
export const KEY_PREFIX = 'tbk_';

/** Bytes of randomness in the key body (after the prefix). 24 bytes → 48 hex chars → ~192 bits. */
const KEY_RANDOM_BYTES = 24;

/** Length kept in plaintext on the `key_prefix` column. Enough to recognize, not enough to use. */
const VISIBLE_PREFIX_LEN = 12;

export interface CreatedKey {
  /** The full plaintext key. Show it to the user ONCE; we don't store it. */
  key: string;
  record: ApiKey;
}

export interface CreateKeyInput {
  email: string;
  name: string;
  purpose?: string;
}

export function generatePlainKey(): string {
  return KEY_PREFIX + randomBytes(KEY_RANDOM_BYTES).toString('hex');
}

/**
 * Hash an API key for storage and lookup.
 *
 * SHA-256 is intentional here (not bcrypt/scrypt/argon2). The plaintext is a
 * 192-bit cryptographically random token generated by us — it is *not* a
 * user-chosen password. The threat model for password hashing (low-entropy
 * inputs susceptible to GPU brute force) does not apply: an attacker who
 * obtains a stored hash would need to enumerate 2^192 candidates, which is
 * computationally infeasible regardless of hash function.
 *
 * Using a slow KDF here would impose ~100 ms per request without any security
 * benefit. SHA-256 keeps the auth path fast and is exactly what GitHub,
 * Stripe, OpenAI etc. use for their API keys. See OWASP "API key cheat sheet".
 *
 * lgtm [js/insufficient-password-hash]
 */
export function hashKey(plainKey: string): string {
  return createHash('sha256').update(plainKey).digest('hex');
}

export function visiblePrefix(plainKey: string): string {
  return plainKey.slice(0, VISIBLE_PREFIX_LEN);
}

/** Creates a new active key. Returns both the plaintext (one-time) and the DB record. */
export async function createKey(
  d: Database,
  input: CreateKeyInput,
): Promise<CreatedKey> {
  const plain = generatePlainKey();
  const rows = await d
    .insert(apiKeys)
    .values({
      keyHash: hashKey(plain),
      keyPrefix: visiblePrefix(plain),
      email: input.email.trim().toLowerCase(),
      name: input.name.trim(),
      purpose: input.purpose?.trim() ?? null,
      tier: 'free',
    })
    .returning();
  const record = rows[0]!;
  return { key: plain, record };
}

/** Returns the active (non-revoked) API key matching the supplied plaintext, or undefined. */
export async function findActiveByPlainKey(
  d: Database,
  plainKey: string,
): Promise<ApiKey | undefined> {
  if (!plainKey.startsWith(KEY_PREFIX)) return undefined;
  const rows = await d
    .select()
    .from(apiKeys)
    .where(
      and(eq(apiKeys.keyHash, hashKey(plainKey)), isNull(apiKeys.revokedAt)),
    )
    .limit(1);
  return rows[0];
}

/**
 * Bumps the per-key counters in one round trip plus the daily histogram in
 * another. Two statements total; both are fire-and-forget from the caller's
 * perspective (the request handler doesn't await this).
 *
 * The histogram entry uses ON CONFLICT DO UPDATE so concurrent requests on
 * the same (key_id, today) row coalesce safely without explicit locks.
 *
 * Best-effort by design: the two statements are NOT wrapped in a transaction,
 * so a failure between them can leave `request_count` and the daily histogram
 * slightly out of sync. Usage counters are approximate; this keeps the hot
 * path cheap and is acceptable for the metric's purpose (DB-6).
 */
export async function bumpUsage(d: Database, keyId: number): Promise<void> {
  await d
    .update(apiKeys)
    .set({
      lastUsedAt: sql`now()`,
      requestCount: sql`${apiKeys.requestCount} + 1`,
    })
    .where(eq(apiKeys.id, keyId));

  const today = todayCaracas();
  await d
    .insert(apiKeyUsageDaily)
    .values({ keyId, date: today, count: 1 })
    .onConflictDoUpdate({
      target: [apiKeyUsageDaily.keyId, apiKeyUsageDaily.date],
      set: { count: sql`${apiKeyUsageDaily.count} + 1` },
    });
}

/** Returns daily counters for the last `days` days (inclusive of today). */
export async function getDailyUsage(
  d: Database,
  keyId: number,
  days = 30,
): Promise<ApiKeyUsageDaily[]> {
  const today = todayCaracas();
  const since = addDays(today, -(days - 1));
  return d
    .select()
    .from(apiKeyUsageDaily)
    .where(
      and(eq(apiKeyUsageDaily.keyId, keyId), gte(apiKeyUsageDaily.date, since)),
    )
    .orderBy(desc(apiKeyUsageDaily.date));
}

/** Soft-delete: mark the key revoked. Future requests with it fail auth. */
export async function revokeKey(d: Database, id: number): Promise<boolean> {
  const result = await d
    .update(apiKeys)
    .set({ revokedAt: sql`now()` })
    .where(and(eq(apiKeys.id, id), isNull(apiKeys.revokedAt)))
    .returning({ id: apiKeys.id });
  return result.length > 0;
}

/** Admin listing — paginated for safety. */
export async function listKeys(d: Database, limit = 100): Promise<ApiKey[]> {
  return d.select().from(apiKeys).orderBy(desc(apiKeys.createdAt)).limit(limit);
}
